package models;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by Hyunjun on 2015-05-13.
 */
public class Semantic {
    private static Map<String, String> semantics = null;

    public static void init() {
        semantics = new HashMap<>();
        semantics.put("aapp", "Amino Acid, Peptide, or Protein");
        semantics.put("acab", "Acquired Abnormality");
        semantics.put("acty", "Activity");
        semantics.put("aggp", "Age Group");
        semantics.put("amas", "Amino Acid Sequence");
        semantics.put("amph", "Amphibian");
        semantics.put("anab", "Anatomical Abnormality");
        semantics.put("anim", "Animal");
        semantics.put("anst", "Anatomical Structure");
        semantics.put("antb", "Antibiotic");
        semantics.put("arch", "Archaeon");
        semantics.put("bacs", "Biologically Active Substance");
        semantics.put("bact", "Bacterium");
        semantics.put("bdsu", "Body Substance");
        semantics.put("bdsy", "Body System");
        semantics.put("bhvr", "Behavior");
        semantics.put("biof", "Biologic Function");
        semantics.put("bird", "Bird");
        semantics.put("blor", "Body Location or Region");
        semantics.put("bmod", "Biomedical Occupation or Discipline");
        semantics.put("bodm", "Biomedical or Dental Material");
        semantics.put("bpoc", "Body Part, Organ, or Organ Component");
        semantics.put("bsoj", "Body Space or Junction");
        semantics.put("carb", "Carbohydrate");
        semantics.put("celc", "Cell Component");
        semantics.put("celf", "Cell Function");
        semantics.put("cell", "Cell");
        semantics.put("cgab", "Congenital Abnormality");
        semantics.put("chem", "Chemical");
        semantics.put("chvf", "Chemical Viewed Functionally");
        semantics.put("chvs", "Chemical Viewed Structurally");
        semantics.put("clas", "Classification");
        semantics.put("clna", "Clinical Attribute");
        semantics.put("clnd", "Clinical Drug");
        semantics.put("cnce", "Conceptual Entity");
        semantics.put("comd", "Cell or Molecular Dysfunction");
        semantics.put("crbs", "Carbohydrate Sequence");
        semantics.put("diap", "Diagnostic Procedure");
        semantics.put("dora", "Daily or Recreational Activity");
        semantics.put("drdd", "Drug Delivery Device");
        semantics.put("dsyn", "Disease or Syndrome");
        semantics.put("edac", "Educational Activity");
        semantics.put("eehu", "Environmental Effect of Humans");
        semantics.put("eico", "Eicosanoid");
        semantics.put("elii", "Element, Ion, or Isotope");
        semantics.put("emod", "Experimental Model of Disease");
        semantics.put("emst", "Embryonic Structure");
        semantics.put("enty", "Entity");
        semantics.put("enzy", "Enzyme");
        semantics.put("euka", "Eukaryote");
        semantics.put("evnt", "Event");
        semantics.put("famg", "Family Group");
        semantics.put("ffas", "Fully Formed Anatomical Structure");
        semantics.put("fish", "Fish");
        semantics.put("fndg", "Finding");
        semantics.put("fngs", "Fungus");
        semantics.put("food", "Food");
        semantics.put("ftcn", "Functional Concept");
        semantics.put("genf", "Genetic Function");
        semantics.put("geoa", "Geographic Area");
        semantics.put("gngm", "Gene or Genome");
        semantics.put("gora", "Governmental or Regulatory Activity");
        semantics.put("grpa", "Group Attribute");
        semantics.put("grup", "Group");
        semantics.put("hcpp", "Human-caused Phenomenon or Process");
        semantics.put("hcro", "Health Care Related Organization");
        semantics.put("hlca", "Health Care Activity");
        semantics.put("hops", "Hazardous or Poisonous Substance");
        semantics.put("horm", "Hormone");
        semantics.put("humn", "Human");
        semantics.put("idcn", "Idea or Concept");
        semantics.put("imft", "Immunologic Factor");
        semantics.put("inbe", "Individual Behavior");
        semantics.put("inch", "Inorganic Chemical");
        semantics.put("inpo", "Injury or Poisoning");
        semantics.put("inpr", "Intellectual Product");
        semantics.put("irda", "Indicator, Reagent, or Diagnostic Aid");
        semantics.put("lang", "Language");
        semantics.put("lbpr", "Laboratory Procedure");
        semantics.put("lbtr", "Laboratory or Test Result");
        semantics.put("lipd", "Lipid");
        semantics.put("mamm", "Mammal");
        semantics.put("mbrt", "Molecular Biology Research Technique");
        semantics.put("mcha", "Machine Activity");
        semantics.put("medd", "Medical Device");
        semantics.put("menp", "Mental Process");
        semantics.put("mnob", "Manufactured Object");
        semantics.put("mobd", "Mental or Behavioral Dysfunction");
        semantics.put("moft", "Molecular Function");
        semantics.put("mosq", "Molecular Sequence");
        semantics.put("neop", "Neoplastic Process");
        semantics.put("nnon", "Nucleic Acid, Nucleoside, or Nucleotide");
        semantics.put("npop", "Natural Phenomenon or Process");
        semantics.put("nsba", "Neuroreactive Substance or Biogenic Amine");
        semantics.put("nusq", "Nucleotide Sequence");
        semantics.put("ocac", "Occupational Activity");
        semantics.put("ocdi", "Occupation or Discipline");
        semantics.put("opco", "Organophosphorus Compound");
        semantics.put("orch", "Organic Chemical");
        semantics.put("orga", "Organism Attribute");
        semantics.put("orgf", "Organism Function");
        semantics.put("orgm", "Organism");
        semantics.put("orgt", "Organization");
        semantics.put("ortf", "Organ or Tissue Function");
        semantics.put("patf", "Pathologic Function");
        semantics.put("phob", "Physical Object");
        semantics.put("phpr", "Phenomenon or Process");
        semantics.put("phsf", "Physiologic Function");
        semantics.put("phsu", "Pharmacologic Substance");
        semantics.put("plnt", "Plant");
        semantics.put("podg", "Patient or Disabled Group");
        semantics.put("popg", "Population Group");
        semantics.put("prog", "Professional or Occupational Group");
        semantics.put("pros", "Professional Society");
        semantics.put("qlco", "Qualitative Concept");
        semantics.put("qnco", "Quantitative Concept");
        semantics.put("rcpt", "Receptor");
        semantics.put("rept", "Reptile");
        semantics.put("resa", "Research Activity");
        semantics.put("resd", "Research Device");
        semantics.put("rnlw", "Regulation or Law");
        semantics.put("sbst", "Substance");
        semantics.put("shro", "Self-help or Relief Organization");
        semantics.put("socb", "Social Behavior");
        semantics.put("sosy", "Sign or Symptom");
        semantics.put("spco", "Spatial Concept");
        semantics.put("strd", "Steroid");
        semantics.put("tisu", "Tissue");
        semantics.put("tmco", "Temporal Concept");
        semantics.put("topp", "Therapeutic or Preventive Procedure");
        semantics.put("virs", "Virus");
        semantics.put("vita", "Vitamin");
        semantics.put("vtbt", "Vertebrate");
    }

    public static String getSemantic(String type) {
        if (semantics == null) init();
        return semantics.get(type);
    }
}
